# Generated by Django 5.1.5 on 2025-01-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientsAll',
            new_name='Client',
        ),
    ]
